name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: './worker/package-lock.json'

      - run: npm ci
      - run: npm run format:check
      - run: npm run lint:check
      - run: npm run tsc
      - run: npm test
